version: 0.2

env:
  variables:
    SOFT_FAIL: "true"
    TARGET_URL: "[https://juice-shop.herokuapp.com/](https://juice-shop.herokuapp.com/)"
    DAST_SCAN_SCRIPT: "zap-baseline.py"

phases:
  install:
    runtime-versions:
      python: 3.11

  pre_build:
    commands:
      - echo "Installing AccuKnox ASPM scanner..."
      - pip install https://github.com/accuknox/aspm-scanner-cli/releases/download/v0.13.4/accuknox_aspm_scanner-0.13.4-py3-none-any.whl --break-system-packages

  build:
    commands:
      - |
        echo "Running AccuKnox DAST scan"
        mkdir /tmp/scan-dir
        chmod 777 /tmp/scan-dir
        cd /tmp/scan-dir

        if [ "$SOFT_FAIL" = "true" ]; then
          SOFT_FAIL_ARG="--softfail"
        fi

        ARGS="$DAST_SCAN_SCRIPT -t $TARGET_URL -I "

        echo accuknox-aspm-scanner scan $SOFT_FAIL_ARG dast --command "$ARGS" --container-mode
        accuknox-aspm-scanner scan $SOFT_FAIL_ARG dast --command "$ARGS" --container-mode
        cd -
