version: 2.1

orbs:
  accuknox-scan: accuknox-scan-1/scan@dev:testing

workflows:
  accuknox:
    jobs:
      - accuknox-scan/container:
          context: accuknox-context
          SOFT_FAIL: false
          IMAGE: "gitlab"
          IMAGE_TAG: "test"
          IMAGE_TAR: "image.tar"
          
        
