version: 2.1

orbs:
  accuknox-scan: accuknox-scan-1/scan@dev:testing

workflows:
  accuknox:
    jobs:
      - accuknox-scan/container:
          context: accuknox-context
          SOFT_FAIL: true
          DAST_SCAN_TYPE: "baseline"
          TARGET_URL: "https://juice-shop.herokuapp.com/"
