name: AccuKnox Container Scan

on:
  push:
    branches:
      - all
  workflow_dispatch:
jobs:
  scan-container:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: "Run Accuknox SAST: Opengrep"
        uses: accuknox/sast-scan-opengrep-action@main
        with:
          accuknox_endpoint: ${{ secrets.ACCUKNOX_ENDPOINT }}
          accuknox_token: ${{ secrets.ACCUKNOX_TOKEN }}
          accuknox_label: ${{ secrets.ACCUKNOX_LABEL }}
          soft_fail: true

      #   - name: AccuKnox Secret Scan
      #     uses: accuknox/secret-scan-action@v1.0.1
      #     with:
      #       token: ${{ secrets.ACCUKNOX_TOKEN }}
      #       tenant_id: 3730
      #       label: "SPOC"
      #       endpoint:  "cspm.demo.accuknox.com"
      #       fail: false
      #       use_extended_ruleset: true

        
