name: AccuKnox Opengrep SAST

on:
  push:
    branches:
      - opengrep
  pull_request:
    branches:
      - opengrep
  workflow_dispatch:

jobs:
  accuknox-cicd:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: "Run AccuKnox SAST: Opengrep"
        uses: accuknox/sast-scan-action@latest
        with:
          skip_sonar_scan: false
          sonar_project_key: "ishaanj18_use-cases"
          sonar_org_id: "ishaanj18"
          sonar_token: "dcdee7a7668feabcf1ad6d74cb707ce1b136d18e"
          sonar_host_url: "https://sonarcloud.io"
          accuknox_endpoint: "cspm.dev.accuknox.com" 
          accuknox_token: ${{ secrets.ACCUKNOX_TOKEN }}
          soft_fail: false
